version: "3.8"
services:
  backend:
    container_name: "mock-stock-backend-${VERSION}"
    build: ./backend
    image: "mock-stock-backend-${VERSION}"
    ports:
      - "5000:5000"
    environment:
      - DB_CONNECTION=mongodb://root:9876512345@mockstock-database:27017
  frontend:
    container_name: "mock-stock-frontend-${VERSION}"
    build: ./frontend
    image: "mock-stock-frontend-${VERSION}"
    ports:
      - "80:80"
      - "443:443"
  database:
    container_name: "mock-stock-database"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 9876512345
    ports:
      - "27017:27017"


