version: "3.8"
services:
  backend:
    container_name: "mockstock-backend"
    build: ./backend
    ports:
      - "5000:5000"
  frontend:
    container_name: "mockstock-frontend"
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"

