version: "3.8"
services:
  backend:
    container_name: "mockstock-backend"
    build: ./backend
    image: mock-stock-backend-{VERSION}
    ports:
      - "5000:5000"
  frontend:
    container_name: "mockstock-frontend"
    build: ./frontend
    image: mock-stock-frontend-{VERSION}
    image
    ports:
      - "80:80"
      - "443:443"
  database:
    container_name: "mockstock-database"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 9876512345
    ports:
      - "27017:27017"


