###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "lenoxyyx",
  "password": "1234"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "lenoxy",
  "password": "1234"
}

###
GET http://localhost:5000/stocks


