###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "lenoxyyx",
  "password": "1234"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "asdfghjkl",
  "password": "asdfghjkl"
}

###
GET http://localhost:5000/stocks?top=5

###
GET http://localhost:5000/stocks/AACG

###
PUT http://localhost:5000/stocks/MSFT
Content-Type: application/json

{ "amount": 20 }

###
GET http://localhost:5000/me


